LICENSE
README.md

Use the same license that we use for Sentry and Snuba, per the recommendation
from the open source team. Also make some small updates to README.

Doc cleanup

---

CHANGES.md
README.md
snuba_sdk/expressions.py
snuba_sdk/query.py
snuba_sdk/query_visitors.py
snuba_sdk/visitors.py
tests/test_expression.py
tests/test_invalid_query.py
tests/test_query.py
tests/test_query_visitors.py

- Add the last few missing clauses: having, orderby, limitby, totals.
- I realized that the query needed to be translated into a JSON blob, since
that's what Snuba ultimately expects. That prompted the realization that it
was time to create a QueryVisitor class.
- Add a pretty print and snuba query visitor.

feat(query) Create Query visitor, add missing clauses

---

snuba_sdk/legacy.py
tests/test_legacy.py

Correctly parse functions in the orderby from legacy Snuba queries.

fix(legacy) Support function order by

---

snuba_sdk/legacy.py
tests/test_legacy.py

Should have been org_id not organization_id per the extension in Snuba.

fix(legacy) Use the correct column for organization filters

---

snuba_sdk/conditions.py
snuba_sdk/expressions.py
snuba_sdk/legacy.py
snuba_sdk/query.py
snuba_sdk/query_visitors.py
snuba_sdk/visitors.py
tests/__init__.py
tests/test_condition.py
tests/test_expression.py
tests/test_function.py
tests/test_legacy.py
tests/test_query.py
tests/test_query_visitors.py

Add CurriedFunctions, which initializers as well as parameters, and are
formatted as `function(initializers)(parameters)`. These are accepted all the
same places a Function is allowed. A Function is now a CurriedFunction with no
initializers. This also makes the parameters optional, which is reflected by not
encoding the parameters if they are None.
There is a chunk of tech debt added here: the legacy API doesn't support curried
functions, they are sent as raw strings e.g. ["quantile(0.5)", "duration", None]
On top of this some users of the legacy API are sending functions in this form
as well e.g. ["apdex(300, duration)", None, None]. Snuba uses a regex grammar to
parse these strings, and it seemed overkill to port that to this SDK just for
this legacy use case. So instead the raw …

feat(curried) Add curried functions

---

snuba_sdk/expressions.py
tests/test_column.py
tests/test_query.py

Allow subscriptables (column[key]) in the Column class. If a Column is a
subscriptable, also populate two helper fields column and key.

fix(subscriptables) Allow subscriptables in the columns

---

snuba_sdk/query.py
snuba_sdk/query_visitors.py
snuba_sdk/visitors.py
tests/test_invalid_query.py
tests/test_query.py
tests/test_query_visitors.py

Add the ability to pass another Query in the match clause of a query. Also add
validation for the inner query and to ensure the outer query is only using
fields returned by the inner query. Added a new visitor that can be used to find
all the expressions of a certain type in a query.

feat(subquery) Add subquery support to SDK

---

snuba_sdk/query_visitors.py
tests/test_query.py

This isn't a restriction in current snuba/clickhouse, so it shouldn't be one
in SnQL either.

fix(limitby) Remove limitby in select constraint

---

Makefile
snuba_sdk/column.py
snuba_sdk/conditions.py
snuba_sdk/entity.py
snuba_sdk/expressions.py
snuba_sdk/function.py
snuba_sdk/legacy.py
snuba_sdk/orderby.py
snuba_sdk/query.py
snuba_sdk/query_visitors.py
snuba_sdk/visitors.py
tests/__init__.py
tests/test_column.py
tests/test_condition.py
tests/test_entity.py
tests/test_expression.py
tests/test_function.py
tests/test_invalid_query.py
tests/test_query.py
tests/test_query_visitors.py

Add an alias field to an entity, and add an entity field to a column. This is in
preparation for adding JOIN support. Having Column dependent on Entity forced a
code restructure which was huge as everything uses Column. Move all complex
expressions into their own modules.

feat(column-entity) Add an alias to entity and column 

---

snuba_sdk/expressions.py
snuba_sdk/legacy.py
snuba_sdk/query.py
snuba_sdk/query_visitors.py
snuba_sdk/visitors.py
tests/test_expression.py
tests/test_legacy_api.py

Add a dry_run flag that can be used by SnQL to leverage the same flag in the
legacy implementation.
See https://github.com/getsentry/snuba/pull/1781 for how this will be used.

feat(dry_run) Add a dry_run flag support

---

CHANGES.rst
snuba_sdk/query_visitors.py
tests/test_legacy_api.py

The legacy API uses aliases in the select clause for aggregations. Correctly
validate this case.

fix(legacy) Handle alias columns in the select

---

snuba_sdk/column.py
tests/test_column.py
tests/test_legacy_api.py

Allow underscores at the start of columns/tags per the example from prod.

fix(column) Be less restrictive with tags

---

snuba_sdk/legacy.py
tests/test_legacy.py

Sometimes the legacy API sends single nested conditions. Since that's
effectively the same as doing an AND between the top level conditions and the
nested condition, just promote it to the top level.

fix(legacy) Handle single nested conditions

---

snuba_sdk/function.py
snuba_sdk/query_visitors.py
snuba_sdk/snuba.py
tests/test_legacy_api.py

This fix is to handle legacy queries where some of the expressions are functions
on aliases of other aggregate functions, e.g. `avg(x) AS avg_x, minus(avg_x, 2)`
When checking to see if the second function is an aggregate, also check all the
aggregate aliases found in the first pass of the function. I'm aware that this
will not work if aggregates are nested multiple levels down, but this will have
to do for now.  It also fixes a bug where if there is a non-aggregate function
on a column in the groupby, only the original column needs to be in the groupby,
not the entire expression. E.g. `SELECT count(), toString(stuff) BY stuff`

fix(groupby) Handle legacy queries with nested aliases of aggregates

---

snuba_sdk/expressions.py
snuba_sdk/legacy.py
snuba_sdk/query.py
snuba_sdk/query_visitors.py
snuba_sdk/visitors.py
tests/test_expression.py
tests/test_query_visitors.py

This flag gets automatically set to True when a legacy Snuba query is converted to a SnQL query. Snuba can then track this flag for metrics and for special code cases etc.

ref(legacy) Add a flag to the query for legacy queries

---

snuba_sdk/legacy.py
tests/test_legacy_api.py

Some older discover queries were using backticks around aliases, presumably from
before the AST could properly escape aliases. They're not needed anymore.

fix(legacy) Strip backticks out of aliases

---

snuba_sdk/legacy.py
tests/test_legacy_api.py

There seems to be a bug in Sentry that sends search strings like this, but since
the legacy endpoint would allow this the SDK should make it work. Sometimes a
string is received with a single backslash on the end, which was incorrectly
escaping the single quote around the string and causing a parsing error. If
there is a trailing backslash, escape it.

fix(legacy) Handle weird edge case with escaping

---

snuba_sdk/legacy.py
tests/test_legacy_api.py

The release column is another one that should always be a string, but can be
queried with strings that look like dates/numbers.

fix(legacy) Ensure the release column is always compared to strings

---

CHANGES.rst
snuba_sdk/__init__.py
snuba_sdk/query.py
tests/test_query.py

This is a big time saver for users of the SDK since it cleans the code up and
means that users don't have to hunt down which package certain classes are in.
Some things that are meant for special cases (DryRun, Legacy) are not added.

feat: Allow importing from snuba_sdk directly

---

CHANGES.rst
snuba_sdk/legacy.py
snuba_sdk/visitors.py
tests/test_legacy_api.py
tests/test_scalar.py

The visitor now correctly escapes ' \ and \n. Snuba requires a change to correctly handle these values as well, so once this is in a release, we'll have to coordinate using it in Sentry and Snuba.

fix(escaping) Properly escape strings

---

setup.py

- Fixes the license (it is MIT, not BSD)
- Fixes the author name and email to match other Sentry projects

docs: Fix some inaccuracies in setup.py

---

CHANGES.rst
snuba_sdk/query_visitors.py
tests/test_query.py

This code has been brittle and difficult to follow for a while, but what pushed
this change over the edge was queries being written for sessions. The `sessions`
column in Sentry is an alias for an aggregate function in Snuba, but the SDK
doesn't know that so it treats it as a non-aggregate and gets upset if it's not
included in the group by. So the SDK would need to know about all such aliases
in Snuba and it's just not worth it. Let Snuba handle this validation.

fix(validate) Remove groupby checks

---

CHANGES.rst
snuba_sdk/legacy.py
tests/test_legacy_api.py

Sometimes tag conditions are passed wrapped in functions. In particular with
datetimes, this behaviour in the legacy API was completely ambiguous, and Snuba
would leave the value as a string. In the SnQL translator, it would attempt to
convert the string to a datetime which is incorrect. In order to ensure that
SnQL remains backwards compatible, handle this case as well.

fix(legacy) Try to ensure tag conditions are on strings

---

CHANGES.rst
snuba_sdk/function.py
tests/test_function.py

This came up because Sentry was using `equation[0]` as an alias. Ultimately, since we escape aliases with backticks in Snuba, it didn't seem like I should block any alias, except one that would break our own aliases (hence why I blocked the character set ``[`'"\]``

fix(legacy) Be less restrictive on aliases

---

CHANGES.rst
snuba_sdk/function.py
tests/test_legacy_api.py

Add the few extra characters needed to allow dates in the form
`2021-07-23T06:23:14` in the function name.

fix(legacy) Hardcoded function strings have dates

---

CHANGES.rst
snuba_sdk/conditions.py
snuba_sdk/legacy.py
tests/test_legacy_api.py

If a legacy function contains an infix condition, convert it to a function with
the correct function operator.
Before, if there was a function call like
```
[
"or",
[
["equals", ["release", "abadcafe"]],
["release", "IN", ["fullhash"]],
],
]
```
The second parameter would be evaluated as a function instead of a condition and would throw an Exception.

fix(legacy) Convert infix conditions to functions

---

.pre-commit-config.yaml
CHANGES.rst
Makefile
linter-requirements.txt
snuba_sdk/__init__.py
snuba_sdk/function.py
snuba_sdk/visitors.py
tests/test_function.py
tests/test_lambda.py

Add Lambda and Identifier expressions to the syntax. Lambdas can be used to
build anonymous functions in the form (`x`) -> <transformation>. Identifiers
can be used inside the transformation to reference the identifier(s) in the
lambda. These can be used inside functions to support higher order functions
such as arrayMap.
________
```
Function(
"arrayMap", 
Lambda(
["x"], 
Function(
"toString", 
[Identifier("x")]
)
), 
Column("some_array")
)
```

feat: Add Lambdas and Identifiers expressions

---

CHANGES.rst
linter-requirements.txt
snuba_sdk/expressions.py
tests/test_aliased_expression.py

Adds @ char as an allowed char in an alias as
with the introduction of MRIs as metrics
ingestion names, @ char is added to identify
unit
For more context: https://github.com/getsentry/relay/pull/1215
Also bumps black to `22.3.0` to fix failing CI
https://github.com/psf/black/issues/2964

feat(expressions): Allow @ char in alias regex

---

README.rst
docs-requirements.txt

Sphinx was failing with the error "ImportError: cannot import name 'environmentfilter' from 'jinja2'"
That error is fixed by pinning Jinja2 to <3.1
I did try to update Sphinx to 4.x, but that caused another error:
"Could not import extension sphinx.builders.epub3"
I could not figure out how to fix that error no matter what combination of
packages I installed, so I kept the older version that at least works.

fix: Fix dependency error in Sphinx

---

README.rst

Switch to using the purple Sentry logo in the readme, as the black one does not render well on a black background, which will happen if you are using a dark theme in your GitHub settings.
Since the readme also renders on PyPi, where the system theme is ignored, the purple logo will look good there as well.
Also updated the sentry url to include utm source/medium parameters, as we do on the other repos.
Thanks.
#skip-changelog

chore: Update logo in readme

---

CHANGES.rst
snuba_sdk/column.py
tests/test_column.py

Expands columns regex to accept "/" and "@"
chars to support MRI formats for column names
such as "d:sessions/duration@millisecond"
Counterpart to https://github.com/getsentry/snuba/pull/3045

feat(column): Expand column regex [TET-323]

---

CHANGES.rst
snuba_sdk/request.py
tests/test_request.py

This flag has been useful in the past and we want to revisit it in the Snuba API
to help debug cases of abuse. Add it as an optional parameter so that this won't
break any existing uses of Request. This value should be updated automatically
in the snuba part of the sentry codebase.

feat: Add parent_api flag to the Request

---

.github/workflows/docs.yml

This error was happening in the docs job:
```
Version 3.6 was not found in the local cache
Error: Version 3.6 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```
Update to use 3.8. Tested locally and docs built successfully.

fix(docs) Update to use Python 3.8

---

snuba_sdk/entity.py

Unfortunately issue search is still using the legacy query format for snuba. Adding this entity to
the legacy code so that it'll work in issue search.

feat(issue-platform): Add search_issues entity to `ENTITY_TIME_COLUMNS`

---

CHANGES.rst
snuba_sdk/legacy.py
snuba_sdk/request.py
tests/test_request.py

- As part of the Capacity Management project, we want to consolidate "tenant" (or general grouping of a query eg referrer, org_id, etc) information into a single dictionary in the Request
- This would be passed by Sentry to Snuba, which will use this information to manage capacity (or rate limit) in a more organized and methodical fashion
- As of now there are no constraints on what these tenants can be

feat(CapMan): Add tenant_ids to Request object

---

CHANGES.rst
snuba_sdk/legacy.py
snuba_sdk/request.py
tests/test_request.py

- Making this field required right away makes it so updating the Sentry repo with a new snuba-sdk version creates a huge set of changes which would be very hard to review
- This way also allows teams to pass tenant_ids themselves on their own time

fix(CapMan): `tenant_ids` field now optional to support gradual adoption

---

snuba_sdk/timeseries.py

This PR is responsible for adding some additional setters to the `Timeseries` and `Metric` classes. These setters will be  required by the new metrics layer to handle MRI/public name resolution.

feat(metrics): Add additional setters metric query classes

---

snuba_sdk/metrics_query.py
tests/test_metrics_expressions.py
tests/test_metrics_query.py

The `use_case_id` in `MetricScope` should be type str as stored in ClickHouse.

fix(metrics): Update use_case_id type

---

CHANGES.rst
snuba_sdk/__init__.py
snuba_sdk/metrics_query.py
snuba_sdk/metrics_query_visitors.py
snuba_sdk/metrics_visitors.py
snuba_sdk/query.py
snuba_sdk/timeseries.py
tests/__init__.py
tests/test_metrics_expressions.py
tests/test_metrics_query.py
tests/test_timeseries.py

Add the basic SnQL translators for the MetricsQuery object and all the objects
it uses.
This adds a translator and validator visitor for the MetricsQuery class. It
also changes Timeseries, Metric, Rollup and MetricScope to all be in the same
file, and to not be Expressions. All of these classes return complex types when
being serialized, in that they affect multiple parts of the query separately.
For example, Rollup impacts the conditions as well as the ORDER BY clause. So
each of these classes also has a visitor in a similar way to the query.

feat(metrics) Add translators/validators for MetricsQuery

---

CHANGES.rst
snuba_sdk/metrics_query.py
snuba_sdk/metrics_query_visitors.py
snuba_sdk/metrics_visitors.py
snuba_sdk/timeseries.py
tests/test_metrics_expressions.py
tests/test_metrics_query.py
tests/test_timeseries.py

Fix some bugs and issues with the way queries were being built.
- Add a separate granularity field in the rollup
- This is a mandatory field, and separate from interval
- This allows interval to be arbitrary, meaning arbitrary rollups are now
supported
- Since granularity is mandatory, the restriction is the rollup must have
one of but not both interval and totals
- The rolled up time function is automatically added to the group by
- The query is ordered by the rolled up time automatically
- Support AliasedExpression in the group by of Timeseries and MetricsQuery.
This was a change made to accomodate columns that are indexed. If a groupby
contains a column that is indexed, the result set would have the indexed value
instead of the original value. Using AliasedExpression allows the indexed …

fix(metrics): Changes/bugfixes to support querying from Sentry

---

CHANGES.rst
snuba_sdk/metrics_query_visitors.py
snuba_sdk/metrics_visitors.py
snuba_sdk/timeseries.py
tests/test_metrics_expressions.py
tests/test_metrics_query.py

If the `totals` parameter is true in the `Rollup` when an interval is
specified, the query will set the `TOTALS True` clause on the SnQL query which
will in turn use Clickhouse's WITH TOTALS clause to fetch an extra totals row.

ref(metrics): Add support for the TOTALS clause in MetricsQuery

---

.github/workflows/docs.yml
.gitignore
Makefile
README.md
docs-requirements.txt
docs/.gitignore
docs/_templates/config.mako
docs/_templates/logo.mako
snuba_sdk/__init__.py

Sphinx has a persistent bug in every version tested (including on Python 3.9):
https://github.com/sphinx-doc/sphinx/issues/9243
There seems to be no documented fix for this. Instead of fighting with this,
switch to a simpler documentation engine, [pdoc3](https://pdoc3.github.io/pdoc/doc/pdoc/#gsc.tab=0). This has definitely less
features than Sphinx but is way easier to use.

ref(docs): Switch from Sphinx to pdoc3

---

snuba_sdk/formula.py
snuba_sdk/metrics_query_visitors.py
tests/__init__.py
tests/test_formula.py

This PR is responsible for adding a new `Formula` class (inherits Expression) which will be used to replace `Function` in MetricsQuery objects. Upon implementing the first iteration of the DSL parser (https://github.com/getsentry/snuba-sdk/pull/126), it was discovered that MetricsQuery, Timeseries and Function classes are not defined intuitively with relation to the new DSL grammar and how the nodes are parsed. Practically, it helps to reason about queries by having arbitrary levels of groupbys and filters. Although, in the AST itself, all filters and groupbys will be pushed down. This class aims to simplify the complexity of the `MetricsQuery` by moving those attributes here.

feat(metrics): Add formula class

---

snuba_sdk/timeseries.py
tests/test_timeseries.py

The Timeseries `filter` property should be able to have type `Condition` and/or `BooleanCondition`. This PR is responsible for fixing that.

fix(metrics): Fix Timeseries Filters Validator

---

CHANGES.rst
snuba_sdk/conditions.py
snuba_sdk/dsl/dsl.py
tests/test_dsl.py

The goal is to eventually unify all our metrics with a single method of querying. Right now, how we express filters is different between discover and metrics. We want to close this gap in order to provide a smooth experience across our product. This PR is responsible for updating the MQL grammar to more closely match how discover exposes filters to our users.
* OR filtering
* bracket filters

ref(MQL): Update MQL Grammar to align with Discover Filter Grammar

---

CHANGES.rst
snuba_sdk/__init__.py
snuba_sdk/dsl/dsl.py
snuba_sdk/formula.py
snuba_sdk/metrics_query_visitors.py
snuba_sdk/metrics_visitors.py
tests/test_dsl.py
tests/test_formula.py

First off, note that this is a temporary measure. Formulas don't encode nicely
into SnQL. The main issue with encoding MetricsQuery into SnQL is that the
visitor pattern assumes each component of a query can be encoded into a string,
and then combined together neatly into a query. That's not true of a
MetricsQuery, and especially a Formula, where the encoding of a single
component can impact multiple parts of a query. For example encoding a Metric
object influences the WHERE clause (metric_id filter) and the MATCH clause (for
the entity).
This assumption works much better when encoding MetricsQuery into MQL, since
the components can be encoded and combined together in a seamless way. Until
then, these visitors will have to hack around the restrictions.
This adds a simple SnQL visitor for …

ref(formula) Add SnQL visitor for Formula

---

CHANGES.rst
snuba_sdk/dsl/dsl.py
tests/test_mql.py

This PR is responsible for extending the MQL grammar to support unquoted tag values and the usage of spaces as delimiters in the filter string. The purpose of doing this is to bring MQL closer to the discover grammar in order to provide a cohesive user experience across the sentry product.

feat(mql): Support unquoted tag values and space delimiters in MQL filter

---

CHANGES.rst
snuba_sdk/mql/mql.py
tests/test_mql.py

One of the main uses for metrics is currently quantiles. Those are curried
functions, so MQL needs to support curried functions if it is going to be used
to encode queries being sent to Snuba.
Add curried functions to the MQL grammar that support arbitrary params. The
only use case at the moment is quantiles but it doesn't hurt to be a little
more open in the grammar.
Also rename `dsl` to `mql` to be more consistent.
Also add `(` and `)` to the excluded characters in unquoted strings.

feat(mql) Support curried functions in MQL

---

snuba_sdk/mql/mql.py
tests/test_mql.py

This PR fixes a small edge case in which the grammar visitor didn't handle the case in which a single condition was inside parentheses.

fix(ddm): Fix MQL grammar handling of single filter nested expressions

---

snuba_sdk/mql/mql.py
tests/test_mql.py

This PR adds the support for `.` in the MQL grammar to handle cases such as `sum(something) by (http.status_code)`.

fix(mql): Add support for `.` in the grammar

---

CHANGES.rst
snuba_sdk/metrics_visitors.py
snuba_sdk/mql_visitor.py
snuba_sdk/visitors.py
tests/test_metrics_query.py
tests/test_mql.py
tests/test_request.py

MQL is meant to align with Discover syntax as much as possible. Discover uses
double quotes instead of single quotes, so when a MetricsQuery is serialized it
needs to be serialized using double quotes instead of single quotes.

fix(mql): Have MQL use double instead of single quotes

---

CHANGES.rst
snuba_sdk/formula.py
snuba_sdk/metrics_visitors.py
snuba_sdk/mql/mql.py
snuba_sdk/mql_visitor.py
tests/test_formula.py
tests/test_formula_printer.py
tests/test_metrics_mql_query.py
tests/test_mql.py

This PR adds a visitor that will encode a Formula to MQL. It supports nested
Formulas as well.
Also, even though the parser supported parsing Formulas from MQL, the tests
were all disabled. The tests were enabled, and used as a basis for all the
other test for serializing Formulas.
For testing, when a Formula is serialized to MQL, the test also checks that the
output MQL can be deserialized back to an SDK object.
An explicit decision was made to not do reverse testing when deserializing MQL.
That's because the range of possible inputs that can be correctly deserialized
is much broader than the set of possible outputs from serializing. For example,
`((((((sum(foo)))))))` is valid input, but when that is serialized it won't
match.

feat(mql): Support encoding Formulas to MQL

---

CHANGES.rst
snuba_sdk/formula.py
snuba_sdk/metrics_visitors.py
snuba_sdk/mql/mql.py
tests/test_formula.py
tests/test_formula_printer.py
tests/test_metrics_mql_query.py
tests/test_mql.py

This PR is responsible for supporting arbitrary functions names and parameters in MQL grammar. Since these functions are what the UI will interact with, they need to be encoded and parsed out of the MQL.
For example: `apdex(sum(transaction.duration), 500)` becomes
```
Formula(
function_name="apdex",
parameters=[
Timeseries(metric=Metric("transaction.duration")),
500
]
)
```
To accomplish this, `Formula.operator: ArithmeticOperator` was changed to `Formula.function_name: str` in order to extend the `Formula` class to handle arbitrary functions. This change also supports serializing back into MQL
Unit tests for parsing MQL to MetricsQuery and MetricsQuery to MQL were added for arbitrary functions.

feat(mql): Support arbitrary functions in MQL Grammar

---

CHANGES.rst
snuba_sdk/mql/mql.py
snuba_sdk/visitors.py
tests/test_metrics_mql_query.py
tests/test_mql.py

The double quote character needs to be escaped when a string is encoded in MQL,
and needs to be decoded when a string is parsed in MQL.

fix(mql) Quotes were not being properly escaped in MQL strings

---

CHANGES.rst
snuba_sdk/mql/mql.py
tests/test_mql.py

This PR is responsible for allowing arbitrary names for aggregate and curried_aggregate functions. Although sentry metrics layer resolves aliased aggregates (`p90`, `p75`, `count_uniq`) into valid functions, the MQL translations happens before the resolution. Therefore, we need to allow any name.

bug(MQL): Allow any name for aggregate or curried aggregate in MQL

---

CHANGES.rst
snuba_sdk/formula.py
tests/test_formula.py

This check would fail if a Formula had an empty groupby, but all its
parameters had the same groupby. Fix the check so that a Formula isn't checked
if its groupby is empty.

fix(formulas) Fix check for inconsistent groupby in Formulas

---

CHANGES.rst
snuba_sdk/formula.py
snuba_sdk/metrics_visitors.py
snuba_sdk/mql/mql.py
snuba_sdk/timeseries.py
tests/__init__.py
tests/test_metrics_mql_query.py
tests/test_mql.py

This PR is responsible the following changes:
* Make aggregates require a metric as a parameter
* Allow string params by using `""`
* Uses `Formula` to capture any function that **is not** an aggregate function (arbitrary functions).
* Adding curried arbitrary function support (e.g. `topK(10)(transaction.duration)`).
Need to update the alias resolver in sentry metrics layer code to support this.
See added test cases for what is now supported.

ref(mql): Use `Formula` for aliased aggregates and arbitrary functions

---

CHANGES.rst
snuba_sdk/mql/mql.py
tests/test_mql.py

Right now, curried arbitrary functions only supports one parameter. This PR is responsible for adding support for multiple params in MQL grammar.

bug(mql): Support multiple params for curried arbitrary functions

---

CHANGES.rst
snuba_sdk/mql/mql.py
tests/test_mql.py

This PR adds the support of numbers in the metric names in the MRI for the MQL grammar.

feat(ddm): Add support for numbers in mri

---

CHANGES.rst
snuba_sdk/mql/mql.py
tests/test_mql.py

This PR adds support of uppercase metric names in the snuba-sdk MQL grammar.
This change is linked to: https://github.com/getsentry/sentry/pull/64250

feat(metrics): Allow uppercase metric names

---

CHANGES.rst
snuba_sdk/metrics_visitors.py
snuba_sdk/mql_context.py
snuba_sdk/mql_visitor.py
tests/test_formula.py
tests/test_formula_printer.py
tests/test_metrics_mql_query.py
tests/test_request.py
tests/test_timeseries.py

This PR is responsible for supporting multiple entities in the MQL Context. In order to support multi-type formula queries, the snuba API needs to be able to receive multiple entities to determine which table(s) to query. To accomplish this, store a mapping of the metric_names (mri or public_name) and entities in the context.

feat(mql): Support multiple entities in MQL Context

---

CHANGES.rst
snuba_sdk/metrics_query.py
snuba_sdk/metrics_query_visitors.py
snuba_sdk/metrics_visitors.py
snuba_sdk/mql/mql.py
snuba_sdk/mql_visitor.py
tests/test_formula_printer.py
tests/test_metrics_mql_query.py
tests/test_mql.py

Allow providing a MQL string as the `query` parameter to a MetricsQuery. The
string will get parsed and validated when being serialized to ensure that it's
a valid MQL string.
Since an MQL string can't specify an entity, this requires that Snuba can
automatically infer the entity based on the passed in MRI. See https://github.com/getsentry/snuba/pull/5501
This also refactored a lot of tests: `parse_mql` was wrapping the parsed
value in a MetricsQuery object. Returning the Formula/Timeseries directly
meant gently refactoring a lot of tests.

feat: Support MQL strings in MetricsQuery

---

snuba_sdk/mql/mql.py
tests/test_mql.py

This PR fixes the missing implementation of the `expression` visitor that didn't generate the right AST for summations and subtractions. In addition, it implements the correct left associativity of both `expression` and `term`.

fix(mql): Fix missing handling of expressions and implement associativity

---

CHANGES.rst
README.md
README.rst
snuba_sdk/formula.py
snuba_sdk/metrics_visitors.py
snuba_sdk/mql_context.py
snuba_sdk/mql_visitor.py
snuba_sdk/timeseries.py
tests/test_formula.py
tests/test_formula_printer.py
tests/test_metrics_mql_query.py
tests/test_request.py
tests/test_timeseries.py

Snuba is now able to parse the entity from the MRI that is passed in. So there
is no need to encode the MRI in the SDK at all. This simplifies the SDK quite a
bit, and also properly enables using raw MQL strings in the SDK.

feat(mql): Remove entity from Metrics SDK

---

CHANGES.rst
snuba_sdk/mql/mql.py
tests/test_mql.py

This PR fixes the grammar for filters, which misused quantifiers allowing filters without being surrounded by `{}`. The new grammar makes filter definitions unambiguous.
An example that would show the ambiguity of the grammar is as follows:
`rate(count(g:custom/zone.domains@none))`
which results in:
`Timeseries(metric=Metric(public_name='count', mri=None, id=None), aggregate='rate', aggregate_params=None, filters=[Condition(lhs=Column(name='g', entity=None, subscriptable=None, key=None), op=<Op.EQ: '='>, rhs='custom/zone.domains@none')], groupby=None)` which is clearly wrong.
The new grammar will output the correct result, that is, a `Formula` of `function_name=rate` containing a `Timeseries`.

fix(mql): Fix ambiguous grammar for filters

---

snuba_sdk/mql/mql.py
tests/test_mql.py

This PR adds support for unary operator `-` on numeric scalars and timeseries/formulas, which was requested by some users.

feat(mql): Add support for unary operator

---

CHANGES.rst
snuba_sdk/formula.py
snuba_sdk/metrics_visitors.py
tests/test_metrics_mql_query.py

This PR implements the missing part of the unary implementation, that is, the serialization of `-` when generating mql from the ast.

fix(mql): Add support for negation in mql visitor

---

.vscode/settings.json
snuba_sdk/metrics_query.py
snuba_sdk/query.py
snuba_sdk/query_optimizers/or_optimizer.py
tests/test_metrics_mql_query.py
tests/test_mql.py
tests/test_or_optimizer.py

This PR adds an optimizer pass to the Query and MetricsQuery during serialization. 
It will take a condition: `c=val1 or c=val2 or c=val3...` and convert it to `c in [val1, val2, val3, ...]`.
This change should fix --at least some of the queries causing-- the recursion bug in parsing.
* I wrote unit tests for the OrOptimizer to verify it optimizes ConditionGroups as expected. 
* I wrote more "end-to-end" tests of `serialize` that verify Query and MetricsQuery are optimized as expected when serialize is called.
* I wrote a test in sentry that sends an MQL query that caused the recursion bug previously. This test doesn't cause the error anymore. Note, this test is not committed to any repo it only exists locally in my own branch. https://github.com/getsentry/sentry/blob/560fe2f33afe0448b13ad …

feat: sdk or optimizer

---

snuba_sdk/mql/mql.py
tests/test_mql.py

This PR adds a more lenient MRI regex to relax the definition, as done in the backend: https://github.com/getsentry/sentry/pull/68175.
The definition of the unquoted MRI is slightly different than the one in the backend since we have to disambiguate certain strings which make the parser confused. The divergence of MRI regexes might cause problems in case some ill-defined metrics are accepted by Relay, the backend, and not by MQL. This however should not happen, but it is a possibility.
In the case of a quoted MRI, an even more lenient version is permitted, since we use backticks to disambiguate and we can therefore afford to put more accepted characters.

feat(ddm): Add lenient MRI regex

---

snuba_sdk/request.py

`dict` is invariant and does not allow mappings of either union to be passed

type tenant_ids as Mapping for variance

---

snuba_sdk/delete_query.py
tests/test_delete_query.py

This PR adds a new subclass of `BaseQuery`, called `DeleteQuery`. This will be used inside a `Request` object for sdk users to create delete queries to send to snuba. Like this:
```
request = Request(
dataset = "search_issues",
app_id = "myappid",
tenant_ids = {"referrer": "my_referrer", "organization_id": 1234}
query = DeleteQuery(
storage="search_issues"
columnConditions={
"project_id": [1],
"occurrence_id": UUID
}
)
)
raw_snql_query(request, ...)
```
Next Steps: 
* change `raw_snql_query` to know what to do when the query type of a request is DeleteQuery
* update snuba to the new sdk

feat: new BaseQuery, DeleteQuery which will be used to make delete queries

---

snuba_sdk/delete_query.py
snuba_sdk/request.py
tests/test_delete_query.py

The SDK was used to connect sentry to a delete endpoint in snuba. We ran into an issue however where the SDK was serializing the body of the request into a str when our data is actually a dict. This change makes it send the object as a dict now instead of a str.
Additionally we want to not send the dataset since its not required for this endpoint.

fix: DeleteQuery, send query as a dict

---

snuba_sdk/entity.py

We need this for [this query](https://github.com/getsentry/sentry/blob/a49edf8ae43666338ccb0d9992fd4e7148c8fb13/src/sentry/tagstore/snuba/backend.py#L318) in Sentry's tagstore backend. Currently the `replays` entity does not support auto-filling the timestamp conditions, and we get 400 bad request, `"detail": "Missing >= condition with a datetime literal on column timestamp for entity replays. Example: timestamp >= toDateTime('2023-05-16 00:00')"`.
(The autofilling is done in snuba_sdk's `json_to_snql` function.)
Impact: we can't search for custom tags in the replays dataset until we release this, and bump sentry's snuba-sdk version.

feat(replay): add replays required timestamp col to ENTITY_TIME_COLUMNS

---

snuba_sdk/query.py

Serializing multiple queries in multiple threads is not thread safe. The `PRINTER` [global](https://github.com/getsentry/snuba-sdk/blob/main/snuba_sdk/query.py#L20) is reused by the Query serializer across these requests and maintains a local `Translator` in the `translator` classvar.
This would be fine if the `translator` were never mutated. However, the `visit` function temporarily mutates the `translator` using `entity_aliases()`.
If multiple queries are being serialized concurrently, there are bad inverleavings of this code that result in invalid queries.
This can be reproduced with this diff and some long running queries issued in a batch ([example](https://www.notion.so/sentry/Querylog-investigation-for-invalid-requests-in-JOIN-for-group-attributes-table-1128b10e4b5d804196f6e261f586a …

fix(query): Make query serialization thread-safe
